name: Release

on:
  push:
    branches:
      - release

env:
  CARGO_TERM_COLOR: always

jobs:
  release:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
    - name: Cache cargo registry
      uses: actions/cache@v5
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v5
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo build
      uses: actions/cache@v5
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    - name: Build release
      run: cargo build --release
    - name: Create release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        SHA: ${{ github.sha }}
      shell: pwsh
      run: |
        $TAG = "release"
        $files = @(
          "target\release\csgo-inventory-editor.exe",
          "target\release\csgo_gc"
        )

        gh release delete "$TAG" --cleanup-tag --repo "$REPO" --yes 2>$null

        Start-Sleep -Seconds 10

        gh release create "$TAG" --repo "$REPO" `
          --title "Rolling Release" `
          --notes "$SHA"

        foreach ($file in $files) {
          if (Test-Path $file) {
            gh release upload "$TAG" --repo "$REPO" --clobber $file
          }
        }
