name: Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
    - name: Cache cargo registry
      uses: actions/cache@v5
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v5
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo build
      uses: actions/cache@v5
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    - name: Build release
      run: cargo build --release
    - name: Prepare artifact
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path artifact
        Copy-Item target/release/csgo-inventory-editor.exe artifact/
        Copy-Item -Recurse target/release/csgo_gc artifact/
        Compress-Archive -Path artifact/* -DestinationPath csgo-inventory-editor-windows-x86_64.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: csgo-inventory-editor-windows-x86_64
        path: csgo-inventory-editor-windows-x86_64.zip
        retention-days: 30
